---
- name: Copy agent to dest host and run it
  hosts: test-agent
  become: yes
  become_user: root
  tasks:
    - name: Copy agent to remote host
      ansible.builtin.copy:
        src: ../../src/agent
        dest: /opt/PilotGo/agent/PilotGo-agent
        owner: root
        group: root
        mode: '0540'

    - name: restart PilotGo agent service
      service:
        name: PilotGo-agent
        state: restarted
      become: yes
      become_user: root