---
- name: install PilotGo platform
  hosts: standalone
  become: yes
  become_user: root
  tasks:
    - name: install redis 6 through euler repo
      dnf: 
        name: redis6-6.2.7-3
        state: present
    - name: restart redis service
      service: 
        name: redis
        state: restarted