---
- name: install PilotGo platform
  hosts: standalone
  become: yes
  become_user: root
  tasks: 
    - name: check redis rpm
      shell: rpm -qa | grep -e '^redis*4*'
      register: rpm_info
      ignore_errors: yes
    - name: uninstall redis4
      dnf: 
        name: redis
        state: absent
      when: rpm_info.rc == 0
    - name: install redis 6 through euler repo
      dnf: 
        name: redis6
        state: present
      ignore_errors: yes
    - name: change bind
      lineinfile: 
        path: /etc/redis/redis.conf
        regexp: '^#?bind'
        line: 'bind {{ groups["standalone"][0] }}'
        backrefs: yes
    - name: change daemonize
      lineinfile: 
        path: /etc/redis/redis.conf
        regexp: '^#?daemonize'
        line: 'daemonize yes'
        backrefs: yes
    - name: change passwd
      lineinfile: 
        path: /etc/redis/redis.conf
        regexp: '^#?requirepass'
        line: 'requirepass {{ redis_password }}'
        backrefs: yes
    - name: restart redis service
      service: 
        name: redis
        state: restarted
    - name: install mysql through euler repo
      dnf: 
        name: "{{ item }}"
        state: present
      with_items: 
        - mysql-server
        - python3-pexpect
      ignore_errors: yes
    - name: start mysql
      service:
        name: mysqld
        state: restarted
    - name: change passwd
      expect: 
        command: mysqladmin -u root -p password '{{ mysql_password }}'
        responses: 
          (?i)password: "\n"
      vars: 
        ansible_python_interpreter: /usr/bin/python3
      register: info
      ignore_errors: yes
    - name: change passwd
      debug: 
        msg: '{{ info.stdout_lines }} mysql already has password'
      when: info.rc != 0
    - name: install pilotgo-server
      dnf: 
        name: PilotGo-server
        state: present
      register: pilotgo_info
      ignore_errors: yes
    - name: exit when pilotgo-server fail install
      fail:  
        msg: 'dnf install PilotGo-server failed'
      when: pilotgo_info.rc != 0
    - name: change PilotGo config
      shell: sed -i '/^http_server:/,+1 s/0\.0\.0\.0/{{ groups['standalone'][0] }}/' /opt/PilotGo/server/config_server.yaml
    - name: change PilotGo config
      shell: sed -i '/^socket_server:/,+1 s/0\.0\.0\.0/{{ groups['standalone'][0] }}/' /opt/PilotGo/server/config_server.yaml
    - name: change PilotGo config
      shell: sed -i '/^mysql:/,+1 s/localhost/{{ groups['standalone'][0] }}/' /opt/PilotGo/server/config_server.yaml
    - name: change passwd
      lineinfile: 
        path: /opt/PilotGo/server/config_server.yaml
        regexp: '^#?password'
        line: '  password: {{ mysql_password }}'
        backrefs: yes
    - name: change PilotGo config
      shell: sed -i '/^redis:/,+1 s/localhost/{{ groups['standalone'][0] }}/' /opt/PilotGo/server/config_server.yaml
    - name: change passwd
      lineinfile: 
        path: /opt/PilotGo/server/config_server.yaml
        regexp: '^#?redis_pwd'
        line: '  redis_pwd: {{ redis_password }}'
        backrefs: yes
    