basePath: /api/v1
definitions:
  gitee_com_openeuler_PilotGo_cmd_server_app_service_user.UserInfo:
    properties:
      departId:
        type: integer
      departName:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      phone:
        type: string
      roleId:
        type: string
      username:
        type: string
    required:
    - email
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a pilotgo server API docs.
  license:
    name: MulanPSL2
    url: http://license.coscl.org.cn/MulanPSL2
  title: PilotGo Swagger  API
  version: "1.0"
paths:
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口,返回用户信息和token
      parameters:
      - description: 用户登录信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/gitee_com_openeuler_PilotGo_cmd_server_app_service_user.UserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            type: string
        "400":
          description: 请求参数错误
          schema:
            type: string
      summary: 用户登录
      tags:
      - user
swagger: "2.0"
