http_server:
  addr: 0.0.0.0:8888 
  use_https: false
  cert_file: ""
  key_file: ""
  session_count: 100
  max_age: 1800
  # if true, will start pprof on :6060
  debug: false
socket_server:
  addr: 0.0.0.0:8879
jwt:
  secret_key: ""
log:
  level: debug
  driver: stdout #可选stdout和file。stdout：输出到终端控制台；file：输出到path下的指定文件。
  path: ./log/pilotgo_server.log
  max_file: 1
  max_size: 10485760
mysql:
  host_name: mysql
  port: 3306
  user_name: 'root'
  password: 'u3bd99dMNFKQ3Wi9'
  data_base: PilotGo
redis:
  redis_conn: redis:6379
  redis_pwd: '12345678'
  use_tls: false
  defaultDB: 0
  dialTimeout: 10s #redis连接超时时间.默认5s
  enableRedis: true #是否启用redis
storage:  #文件服务存储路径
  path: "/opt/PilotGo/server/data"
